// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwjZJ41Kka7XDumVIXCR_HEElxXBDrNQ',
    appId: '1:759286514292:web:bc4cdd8edb570d5f418721',
    messagingSenderId: '759286514292',
    projectId: 'percobaan-895c6',
    authDomain: 'percobaan-895c6.firebaseapp.com',
    storageBucket: 'percobaan-895c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaAa9qHzUHtMTdDuZDB3LvzM4l9Y3gYj8',
    appId: '1:759286514292:android:da1846c74dedc606418721',
    messagingSenderId: '759286514292',
    projectId: 'percobaan-895c6',
    storageBucket: 'percobaan-895c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pfeCuT9xr0Ti_F3vZaAUhlSihy0duQg',
    appId: '1:759286514292:ios:bad27b4938e01554418721',
    messagingSenderId: '759286514292',
    projectId: 'percobaan-895c6',
    storageBucket: 'percobaan-895c6.firebasestorage.app',
    iosBundleId: 'com.example.praktikumtambahan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9pfeCuT9xr0Ti_F3vZaAUhlSihy0duQg',
    appId: '1:759286514292:ios:bad27b4938e01554418721',
    messagingSenderId: '759286514292',
    projectId: 'percobaan-895c6',
    storageBucket: 'percobaan-895c6.firebasestorage.app',
    iosBundleId: 'com.example.praktikumtambahan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEwjZJ41Kka7XDumVIXCR_HEElxXBDrNQ',
    appId: '1:759286514292:web:cb8059f233df5980418721',
    messagingSenderId: '759286514292',
    projectId: 'percobaan-895c6',
    authDomain: 'percobaan-895c6.firebaseapp.com',
    storageBucket: 'percobaan-895c6.firebasestorage.app',
  );

}